name: CI-CD
on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Run Hardhat Tests
        run: npx hardhat test
        env:
          ALCHEMY_ETH_API_KEY: ${{ secrets.ALCHEMY_ETH_API_KEY }}
          ETH_PINNED_BLOCK: 13433444
      - name: Package for NPM
        run: npm run package
      - name: Publish to NPM
        run: npm publish dist --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

