name: CI-CD
on:
  push:
    branches:
      - "*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm install
      - name: Run Hardhat Tests
        env:
          ALCHEMY_ETH_API_KEY: ${{ secrets.ALCHEMY_ETH_API_KEY }}
          ETH_PINNED_BLOCK: 13433444
        run: npx hardhat test

  deploy:
    name: Publish to NPM
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-and-test
    steps:
      - name: Package for NPM
        run: npm run package
      - name: Publish to NPM
        run: |
          npm config set ::add-mask:://registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
          npm publish dist --access public

